remote_theme: brunochanrio/material-jekyll-chanrio@2025.04.04
plugins:
- jekyll-remote-theme

title: Bruno-chanrio
author: Bruno-chanrio
logo: "assets/Bruno-chanrio_TitleBarLogo_Colorful_Dark.png"
mobilelogo: "assets/Bruno-chanrio_Icon.png"



baseurl: "/"
color: "#FF6ABF"
head-theme-color: "#D70082"
accentColor: pink
themeColor: pink
fixedNav: 'true' # true or false

github_user: "brunochanrio"

permalink: /:year/:title/
markdown: kramdown
exclude: [_site, CHANGELOG.md, LICENSE, vendor]

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path

# Defaults
defaults:
  - scope:
      path: "_docs"
      type: "docs"
    values:
      layout: page
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: "posts"
      type: "posts"
    values:
      layout: "post"
