remote_theme: brunochanrio/mkdocs-jekyll@1.2.1
plugins:
- jekyll-remote-theme

title: Bruno-chanrio Main Website
author: Bruno-chanrio
logo: "Cff6b53b589834a42ca86a6e85250f0a9 (2) (1).png"



baseurl: "/"
color: "#1DE9B6"
accentColor: pink
themeColor: pink
fixedNav: 'false' # true or false

github_user: "brunochanrio"

permalink: /:year/:title/
markdown: kramdown
exclude: [_site, CHANGELOG.md, LICENSE, vendor]

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path

# Defaults
defaults:
  - scope:
      path: "_docs"
      type: "docs"
    values:
      layout: page
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: "posts"
      type: "posts"
    values:
      layout: "post"
